# Changing this file necessitates a server restart
name: "ACCESS-NRI MED Portal"
abbreviation: "medportal"
issn: "0000-0000"
tagline: "a cookbook of code examples to be used for model evaluation and diagnostics for ACCESS-NRI."
logo_url: "https://medportal-dev-6a745f452687.herokuapp.com/logo_large.jpg"
url: "https://medportal-dev-6a745f452687.herokuapp.com"
editor_email: "none@example.com"
noreply_email: "none@example.com"
launch_date: "2016-05-05"
twitter: "@JOSS_TheOJ"
mastodon_url: "https://fosstodon.org/@JOSS"
google_analytics: "UA-47852178-4"
github: "ACCESS-NRI/MED-Portal"
reviews: "ACCESS-NRI/med-reviews"
papers_repo: "ACCESS-NRI/med-recipes"
papers_html_url: "https://raw.githubusercontent.com/ACCESS-NRI/med-recipes/main/"
reviewers_url: "https://reviewers.medportal-dev-6a745f452687.herokuapp.com"
reviewers_signup_url: "https://reviewers.medportal-dev-6a745f452687.herokuapp.com/join"
reviewers_lookup_url: "https://reviewers.medportal-dev-6a745f452687.herokuapp.com/lookup"
product: "software" # the *thing* being submitted for review
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the JOSS submission criteria.
paper_types: []
bot_username: med-oc
features:
  tracks: true
